spring:
    profiles:
        active: dev
    datasource:
        dataSourceClassName: com.mysql.jdbc.jdbc2.optional.MysqlDataSource
        url: jdbc:mysql://localhost:3306/sbtemplate?useUnicode=true&characterEncoding=utf8
        databaseName:
        serverName:
        username: root
        password:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true

    jpa:
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        database: MYSQL
        openInView: false
        show_sql: false
        generate-ddl: false
        hibernate:
            ddl-auto: update
            naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
        properties:
                    hibernate.cache.use_second_level_cache: false
                    hibernate.cache.use_query_cache: false
                    hibernate.generate_statistics: false
                    org.hibernate.envers.audit_table_suffix: _history

endpoints.health.sensitive: false

health:
  rotationConfig:
    persistentFilePath: /var/lib/company/sbtemplate/public/rotation_status.txt

requestLog:
    logTimeZone: IST
    #Commenting it for now to run in local setup
    #logFilename: /var/log/company/sbtemplate/access-yyyy_mm_dd.log
    maxHistory: 6


envConfig:
